export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_MATERIAL = "GET_MATERIAL";
export const GET_ALL_CATEGORY_BY_ID = "GET_ALL_CATEGORY_BY_ID";
export const GET_ALL_SUB_CATEGORY_BY_ID = "GET_ALL_SUB_CATEGORY_BY_ID";
export const GET_ALL_CATEGORY_BY_MATERIAL = "GET_ALL_CATEGORY_BY_MATERIAL";
